// flow-typed signature: 4d760dc594a6dc39ec6f9a7c98b5e4ed
// flow-typed version: <<STUB>>/@agoric/harden_v0.0.4/flow_v0.100.0

/**
 * This @@WAS an autogenerated libdef stub for:
 *
 *   '@agoric/harden'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@agoric/harden' {
  declare function harden<T>(root: T): T;

  declare module.exports: typeof harden;
}
